---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    cosign.sigstore.dev/imageRef: icr.io/gitsecure/grype-vulnerability-scan:v1
  name: grype-vulnerability-scan
spec:
  params:
    - description: image reference
      name: image-ref
    - description: image digest
      name: image-digest
    - default: "0"
      description: toggles debug mode for the pipeline
      name: pipeline-debug
    - default: ssf-vulnerability-report.json
      description: filepath to store the vulnerability report
      name: vulnerability-report-filepath
  results:
    - description: status of syft task, possible value are-success|failure
      name: status
    - description: filepath to store vulnerability report
      name: vulnerability-report
  stepTemplate:
    env:
      - name: PIPELINE_DEBUG
        value: $(params.pipeline-debug)
  steps:
    - args:
        - |
          #!/bin/sh
          if [ "$PIPELINE_DEBUG" == "1" ]; then
            set -x +e
          fi
          imgRef=$(params.image-ref)@$(params.image-digest)
          echo "running vulnerability scan on $imgRef"
          grype $imgRef > vulnerability-report.txt
          cat vulnerability-report.txt
          okMsg="No vulnerabilities found"

          if [ "$okMsg" == "$(cat vulnerability-report.txt)" ] ;then
            exit 0
          else
            exit 1
          fi
      command:
        - /bin/sh
        - -c
      image: icr.io/gitsecure/anchore-grype:0.23
      name: grype-scanner
