# Disable some built-in rules.
no-duplicate-header:
  allow_different_nesting: true
line-length:
  tables: false
  code_blocks: false
single-h1: false
# MD033/no-inline-html - Inline HTML
MD033:
  # Allowed elements
  allowed_elements: [p, img]
