$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
dictionaryDefinitions:
  - name: frsca-words
    path: './frsca-words.txt'
    addWords: true
dictionaries:
  - frsca-words
ignorePaths:
  - '/frsca-words.txt'
  - '/docs/themes'
  - '/go.mod'
  - '/platform/vendor'
  - 'frsca_tool.cue'
  - 'go.sum'
  - 'cue.mod'
  - '*.cue'
