apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy-pipeline
spec:
  workspaces:
    - name: git-source
      description: The git repo
  params:
    - name: gitUrl
      description: Git repository url
    - name: gitRevision
      description: Git revision to check out
      default: master
    - name: pathToContext
      description: The path to the build context, used by Kaniko - within the workspace
      default: src
    - name: pathToYamlFile
      description: The path to the yaml file to deploy within the git source
    - name: imageUrl
      description: Image name including repository
    - name: imageTag
      description: Image tag
      default: "latest"
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: git-source
      params:
        - name: url
          value: "$(params.gitUrl)"
        - name: revision
          value: "$(params.gitRevision)"
        - name: subdirectory
          value: "."
        - name: deleteExisting
          value: "true"
    - name: source-to-image
      taskRef:
        name: kaniko
      runAfter:
        - clone-repo
      workspaces:
        - name: source
          workspace: git-source
      params:
        - name: CONTEXT
          value: $(params.pathToContext)
        - name: IMAGE
          value: $(params.imageUrl):$(params.imageTag)
    # - name: source-to-image
    #   taskRef:
    #     name: docker-build
    #   runAfter:
    #     - clone-repo
    #   workspaces:
    #     - name: source
    #       workspace: git-source
    #   params:
    #     - name: context
    #       value: $(params.pathToContext)
    #     - name: dockerfile
    #       value: $(params.pathToContext)/Dockerfile
    #     - name: image
    #       value: $(params.imageUrl):$(params.imageTag)
    # - name: source-to-image
    #   taskRef:
    #     name: buildkit-daemonless
    #   runAfter:
    #     - clone-repo
    #   workspaces:
    #     - name: source
    #       workspace: git-source
    #   params:
    #     - name: DOCKERFILE
    #       value: $(params.pathToContext)/Dockerfile
    # - name: deploy-to-cluster
    #   taskRef:
    #     name: deploy-using-kubectl
    #   workspaces:
    #     - name: git-source
    #       workspace: git-source
    #   params:
    #     - name: pathToYamlFile
    #       value: $(params.pathToYamlFile)
    #     - name: imageUrl
    #       value: $(params.imageUrl)
    #     - name: imageTag
    #       value: $(params.imageTag)
    #     - name: imageDigest
    #       value: $(tasks.source-to-image.results.IMAGE-DIGEST)
