---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: maven-test-pipeline-run-
spec:
  pipelineRef:
    name: maven-test-pipeline
  workspaces:
    - name: maven-settings
      emptyDir: {}
    - name: shared-workspace
      persistentvolumeclaim:
        claimName: maven-source-pvc
