tetragon:
  # Allowlist for JSON export. For example, to export only process_connect events from
  # the default namespace:
  #
  # exportAllowList: |
  #   {"namespace":["default"],"event_set":["PROCESS_EXEC"]}
  exportAllowList: |-
    {"event_set":["PROCESS_EXEC", "PROCESS_EXIT", "PROCESS_KPROBE"]}

  # Denylist for JSON export. For example, to exclude exec events that look similar to
  # Kubernetes health checks and all the events from kube-system namespace and the host:
  #
  # exportDenyList: |
  #   {"health_check":true}
  #   {"namespace":["kube-system",""]}
  #
  exportDenyList: |-
    {"health_check":true}
    {"namespace":["", "spire", "kube-system"]}

  # Access Kubernetes API to associate Tetragon events with Kubernetes pods.
  enableK8sAPI: true
  # enableProcessCred enables Capabilities visibility in exec and kprobe events.
  enableProcessCred: true

  # enableProcessNs enables Namespaces visibility in exec and kprobe events.
  enableProcessNs: true

  prometheus:
    # -- Whether to enable exposing Tetragon metrics.
    enabled: false
    # -- The port at which to expose metrics.