---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitea-http-cert
spec:
  commonName: gitea-http
  secretName: gitea-http-certs
  duration: 336h     # 14 days
  renewBefore: 168h  #  7 days
  dnsNames:
    - gitea-http.gitea.svc.cluster.local
    - gitea-http.gitea
    - gitea-http
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: internal-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
