---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oidc-cert
spec:
  commonName: oidc
  secretName: oidc-cert
  duration: 336h     # 14 days
  renewBefore: 168h  #  7 days
  dnsNames:
    - spire-oidc.spire.svc.cluster.local
    - oidc.example.org
    - oidc
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: internal-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
