---
name: docs
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - ".github/**"
      - "docs/**"
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  docs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: build
        uses: shalzz/zola-deploy-action@2f512f31e2e912d5fbd15f319c9c1bfbcfa90a55  # v0.23.4
        env:
          BUILD_DIR: docs
          BUILD_ONLY: true
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453  # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/public
